In [1]:
print("hello there")

hello there

In [1]:
import panda as pd
print("panda is there")

ModuleNotFoundError: No module named 'request'

In [1]:
import pandas as pd
print("now it's working")

now it's working

In [4]:
import pandas as pd
data={
    "player":["mwanetu","teammates","opponets"]
    "points":[18,12,9]

}
df=pd.DataFrame(data)
df

SyntaxError: invalid syntax. Perhaps you forgot a comma? (544496903.py, line 3)

In [5]:
import pandas as pd

data = {
    "Player": ["You 😎", "Teammate", "Opponent"],
    "Points": [18, 12, 9]
}

df = pd.DataFrame(data)
df

     Player  Points
0     You 😎      18
1  Teammate      12
2  Opponent       9

In [6]:
import pandas as pd

data = {
    "Player": ["Mwanetu", "John", "Alex", "Chris"],
    "Points": [18, 12, 25, 15],
    "Assists": [5, 7, 3, 6],
    "Rebounds": [8, 4, 10, 7]
}

df = pd.DataFrame(data)
df

    Player  Points  Assists  Rebounds
0  Mwanetu      18        5         8
1     John      12        7         4
2     Alex      25        3        10
3    Chris      15        6         7